package com.github.betterbuiltfool.datagen;

import com.github.betterbuiltfool.DynamicFraming;
import com.google.gson.JsonObject;
import net.minecraft.data.CachedOutput;
import net.minecraft.data.DataProvider;
import net.minecraft.data.PackOutput;
import org.jetbrains.annotations.NotNull;

import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

public class AutoLangProvider implements DataProvider {
    public final String DOMAIN = "com.github.betterbuiltfool";
    public final PackOutput packOutput;
    public final Map<String, String> translations = new HashMap<>();
    
    public AutoLangProvider(PackOutput output) {
        packOutput = output;
    }
    
    public String add(String category, String key, String value) {
        String fullKey = category + "." + DynamicFraming.MOD_ID + "." + key;
        translations.put(fullKey, value);
        return fullKey;
    }
    
    @Override
    public @NotNull CompletableFuture<?> run(CachedOutput output) {
        Path jsonPath = packOutput.getOutputFolder().resolve("assets/" + DynamicFraming.MOD_ID + "/lang/en_us.json");
        
        JsonObject jsonTree = new JsonObject();
        
        for (var entry:translations.entrySet()) {
            jsonTree.addProperty(entry.getKey(), entry.getValue());
        }
        
        return DataProvider.saveStable(output, jsonTree, jsonPath).thenRun(() -> {
            try {
                generateJavaConstants();
            } catch (IOException exception) {
                throw new RuntimeException("Failed to automatically generate ModTexts.java constants class", exception);
            }
        });
    }
    
    private void generateJavaConstants() throws IOException {
        String sourcePath = "common/src/main/java/" + DOMAIN.replace(".", "/") + "/init/ModTexts.java";
        
        try (FileWriter writer = new FileWriter(sourcePath)){
            writer.write("package " + DOMAIN + ".init\n\n");
            writer.write("import net.minecraft.network.chat.Component;\n\n");
            writer.write("/* Automatically generated by Data Generation. Do not manually edit! */");
            writer.write("public class ModTexts {\n");
            for (var entry:translations.entrySet()) {
                String varName = entry.getKey()
                                         .replace("." + DynamicFraming.MOD_ID + ".", "_")
                                         .toUpperCase()
                                         .replace(".", "_");
                writer.write("\tpublic static Component " + varName + " = Component.translatable(\"" + entry.getValue() + "\");\n");
            }
            writer.write("}\n");
        }
    }
    
    @Override
    public @NotNull String getName() {
        return "Auto language and Constants generator for " + DynamicFraming.MOD_ID;
    }
}
