package com.github.betterbuiltfool.datagen;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonObject;

import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;

public class AutoLangProvider {
    private static final String MOD_ID = "dynamic_framing";
    private static final Gson GSON = new GsonBuilder()
                                             .setPrettyPrinting()
                                             .disableHtmlEscaping()
                                             .create();
    public static final String DOMAIN = "com.github.betterbuiltfool";
    public final Map<String, String> translations = new HashMap<>();
    
    public String add(Category category, String key, String value) {
        String fullKey = category.getKey() + "." + MOD_ID + "." + key;
        if (translations.containsKey(fullKey)) {
            throw new IllegalArgumentException("Cannot add duplicate key %s to translations".formatted(fullKey));
        }
        translations.put(fullKey, value);
        return fullKey;
    }
    
    public String add(Category category, String subcategory, String key, String value) {
        return add(category, subcategory + "." + key, value);
    }
    
    private void generateJson() throws IOException{
        Path jsonPath = Path.of("common/src/main/resources/assets/" + MOD_ID + "/lang/en_us.json");
        Files.createDirectories(jsonPath.getParent());
        
        JsonObject jsonTree = new JsonObject();
        
        for (var entry:translations.entrySet()) {
            jsonTree.addProperty(entry.getKey(), entry.getValue());
        }
        
        try (var writer = Files.newBufferedWriter(jsonPath)) {
            GSON.toJson(jsonTree, writer);
        }
    }
    
    private void generateJavaConstants() throws IOException {
        String sourcePath = "common/src/main/java/" + DOMAIN.replace(".", "/") + "/init/ModTexts.java";
        
        try (FileWriter writer = new FileWriter(sourcePath)){
            writer.write("package " + DOMAIN + ".init;\n\n");
            writer.write("import net.minecraft.network.chat.Component;\n\n");
            writer.write("/* Automatically generated by Data Generation. Do not manually edit! */\n\n");
            writer.write("public class ModTexts {\n");
            for (var entry:translations.entrySet()) {
                String varName = entry.getKey()
                                      .replace("." + MOD_ID + ".", "_")
                                         .toUpperCase()
                                         .replace(".", "_");
                writer.write("\tpublic static Component " + varName + " = Component.translatable(\"" + entry.getValue() + "\");\n");
            }
            writer.write("}\n");
        }
    }
    
    public static void main(String[] args) {
        try {
            AutoLangProvider provider = new AutoLangProvider();
            
            ModTranslationRegister.register(provider);
            
            provider.generateJson();
            provider.generateJavaConstants();
        }
        catch (IOException e) {
            System.err.println("[Datagen Error] Critical file read/write failure occurred!");
            e.printStackTrace();
        } catch (IllegalArgumentException e) {
            System.err.println("[Datagen Error] Key validation failed! You registered a duplicate key.");
            e.printStackTrace();
        } catch (NullPointerException e) {
            System.err.println("[Datagen Error] Found a null key or value in the translation registry.");
            e.printStackTrace();
        }
    }
}
