package com.github.betterbuiltfool.init;

import net.minecraft.network.chat.Component;

/* Automatically generated by Data Generation. Do not manually edit! */

public class ModTexts {
	public static Component TOOLTIP_FRAMING_HAMMER_SELECTION = Component.translatable("Selection: %s");
	public static Component CONFIG_OPTION_REMOVE_SELECTION_COLOR = Component.translatable("Remove Selection Color");
	public static Component CONFIG_TITLE = Component.translatable("Dynamic Framing Config");
	public static Component CONFIG_OPTION_BLOCK_REPLACEMENT_WHITELIST = Component.translatable("Block Replacement Whitelist");
	public static Component TOOLTIP_FRAMING_HAMMER_FIRST_POS = Component.translatable("First Selected Position: %s");
	public static Component CONFIG_OPTION_STRUCTURE_MATERIAL_WHITELIST = Component.translatable("Valid Structure Materials");
	public static Component ITEM_FROE = Component.translatable("Froe");
	public static Component CONFIG_CATEGORY_STRUCTURE = Component.translatable("Structure");
	public static Component CONFIG_OPTION_STANDARD_EDGE_COLOR = Component.translatable("Normal Line Color");
	public static Component CREATIVE_TAB_TOOLS = Component.translatable("Framing Tools");
	public static Component CONFIG_CATEGORY_BLOCK_VALIDATION = Component.translatable("Block Validation");
	public static Component CONFIG_CATEGORY_NETWORK_VIEW = Component.translatable("Network View");
	public static Component ITEM_FRAMING_HAMMER = Component.translatable("Framing Mallet");
	public static Component CONFIG_OPTION_INVALID_EDGE_COLOR = Component.translatable("Invalid Edge Color");
	public static Component CONFIG_OPTION_VALID_EDGE_COLOR = Component.translatable("Valid Edge Color");
	public static Component CONFIG_OPTION_SELECTION_COLOR = Component.translatable("Selection Color");
}
